# Generated by Django 5.0.4 on 2024-05-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_weeklyschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='arrival_timezone',
            field=models.CharField(choices=[('GMT+12', 'GMT+12'), ('GMT+12:45', 'GMT+12:45'), ('GMT+10', 'GMT+10')], default='GMT+12', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='departure_timezone',
            field=models.CharField(choices=[('GMT+12', 'GMT+12'), ('GMT+12:45', 'GMT+12:45'), ('GMT+10', 'GMT+10')], default='GMT+12', max_length=20),
        ),
    ]
