# Generated by Django 5.0.4 on 2024-05-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_weeklyschedule_arrival_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='return_arrival_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='return_arrival_timezone',
            field=models.CharField(choices=[('GMT+12', 'GMT+12'), ('GMT+12:45', 'GMT+12:45'), ('GMT+10', 'GMT+10')], default='GMT+12', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='return_day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='return_departure_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='return_departure_timezone',
            field=models.CharField(choices=[('GMT+12', 'GMT+12'), ('GMT+12:45', 'GMT+12:45'), ('GMT+10', 'GMT+10')], default='GMT+12', max_length=20),
        ),
    ]
