# Generated by Django 5.0.4 on 2024-05-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_weeklyschedule_return_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='return_arrival_time',
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='return_arrival_timezone',
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='return_day_of_week',
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='return_departure_time',
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='return_departure_timezone',
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='is_return_flight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Every week day', 'Every week day')], max_length=15),
        ),
    ]
