# Generated by Django 5.0.4 on 2024-05-21 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_weeklyschedule_return_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=6, unique=True)),
                ('Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.weeklyschedule')),
            ],
        ),
    ]
