# Generated by Django 5.0.4 on 2024-05-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Schedule',
            new_name='schedule',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
