# Generated by Django 5.0.4 on 2024-05-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_weeklyschedule_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'), (7, 'Every week day')]),
        ),
    ]
