# Generated by Django 5.0.4 on 2024-05-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_weeklyschedule_day_of_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'List of Reservations'},
        ),
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(default='example@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='john', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='doe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='middle_name',
            field=models.CharField(default='middle', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='code',
            field=models.CharField(default='UM123', max_length=100),
            preserve_default=False,
        ),
    ]
