# Generated by Django 5.0.4 on 2024-05-29 01:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_booking_options_booking_contact_booking_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booked_flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField()),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.route')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_flight',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.booked_flight'),
            preserve_default=False,
        ),
    ]
