# Generated by Django 5.0.4 on 2024-05-29 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_booked_flight_booking_booked_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.booked_flight'),
        ),
    ]
